apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: todo
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: openshift
    registry: ghcr.io
  environments:
  - key: dev
    owner: ktrenkelbach
    repository: jx3-openshift
  - key: staging
  - key: production
  ingress:
    domain: apps.okd.dlcdso.com
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: ktrenkelbach
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
